name: reminder_flutter
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  go_router: ^14.1.2
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.18.1
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  timezone: ^0.9.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
