name: reminder_flutter
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  go_router: ^14.1.2
  http: ^1.2.1
  intl: ^0.18.1
  provider: ^6.1.2
  timezone: ^0.9.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
